# Generated by Django 4.1.2 on 2023-03-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image_url',
            field=models.URLField(blank=True, default=False, max_length=300),
        ),
    ]
