# Generated by Django 4.1.2 on 2023-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
